age_list_high = ["age rating", "suitable for", "old enough", "too old for", "too young for", "a U", "a 12", "a 12A",
                 "a 15", "an 18", "a 18"]
age_list_medium = ["rating", "age", "suitable", "old", "young"]
age_list_low = ["U", "12", "12A", "15", "18", "R"]
review_rating_list_high = ["review rating", "a good film", "any good", "how good", "worth watching", "many stars",
                           "very good", "should I watch", "is it good", "is it bad", "good", "bad", "rubbish", "out of"]
review_rating_list_medium = ["rating"]
review_rating_list_low = []
synopsis_list_high = ["plot", "synopsis", "summary", "story"]
synopsis_list_medium = ["about"]
synopsis_list_low = []
trailer_list_high = ["trailer", "advert", "commercial", "preview", "sneak peak"]
trailer_list_medium = []
trailer_list_low = []
genre_list_high = ["type", "sort", "kind", "genre", "style"]
genre_list_medium = []
genre_list_low = []
year_list_high = ["what year", "released", "when was", "how old", "release year", "come out", "when did"]
year_list_medium = []
year_list_low = ["old", "age"]
date_list_high = ["what date", "coming out", "due to", "being released", "be released"]
date_list_medium = ["old", "age", "release", "released"]
date_list_low = []
runtime_list_high = ["how long", "run time", "runtime", "length", "duration"]
runtime_list_medium = []
runtime_list_low = []
director_list_high = ["who directed", "director", "directing"]
director_list_medium = ["made"]
director_list_low = []
writer_list_high = ["wrote", "writer", "written"]
writer_list_medium = ["book", "based on"]
writer_list_low = []
actor_list_high = ["actor", "actress", "starred in", "acting", "acted", "was in", "is in", "cast"]
actor_list_medium = []
actor_list_low = []
awards_list_high = ["awards", "award", "oscar", "emmy", "won", "nominated", "best picture", "best actor", "best actress"
                    , "best director"]
awards_list_medium = []
awards_list_low = []
poster_list_high = ["poster", "artwork"]
poster_list_medium = []
poster_list_low = []
positive_response_list = ["yes", "yep", "yeah", "please", "okay", "ok", "yuh", "why not", "sure", "absolutely",
                          "fine", "yup", "y", "mhm", "ye"]
negative_response_list = ["no", "nope", "nah", "pass", "i'll pass", "nay", "not", "n", "false"]
preceding_keywords_list = ["is", "of", "for", "see", "watch", "view", "rating", "rate", "rated", "score", "does", "be",
                           "in", "watching", "viewing", "seeing", "wrote", "directed", "made", "was", "did", "plot"]
stop_keywords_list = ["nevermind", "never mind", "stop", "return", "pass", "nothing"]
succeeding_keywords_list = ["about", "good", "worth", "a", "an", "come", "plot", "a", "an", "bad"]
